version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew build

reports:
  junit:
    files:
      - '*'
    base-directory: build/test-results/test

artifacts:
  files:
    - '*'
  base-directory: build/distributions

cache:
  paths:
    - '/root/.gradle/**/*'
